json.extract! address, 
  :id, 
  :postal_code,
  :building_number,
  :building_name,
  :road,
  :street_name,
  :floor,
  :province_name,
  :district_name,
  :sub_district_name, 
  :state_name,
  :extra_info,
  :latitude, 
  :longitude, 
  :created_at, 
  :updated_at